name: Deploy Application

on:
  push:
    branches:
      - main # triggers production deployment
      - staging # triggers staging deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Define environment based on the branch
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # You can adjust this to your project's Node version

      - name: Install npm dependencies
        run: npm install # Instead of npm ci which requires package-lock.json

      - name: Build frontend
        run: npm run prod

      - name: Upload files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_KEY }}
          passphrase: ${{ secrets.PROD_SERVER_KEY_PASS }}
          port: 22
          source: "./"
          target: "${{ secrets.PROD_DEPLOY_PATH }}"

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_KEY }}
          passphrase: ${{ secrets.PROD_SERVER_KEY_PASS }}
          port: 22
          script: |
            cd ${{ secrets.PROD_DEPLOY_PATH }}
            cp ../.env .
            composer install --no-interaction
            php artisan view:clear
            php artisan view:cache
            npm run prod
            echo "Deployed successfully"
