name: Deploy Application

on:
  push:
    branches:
      - main # triggers production deployment
      - staging # triggers staging deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Define environment based on the branch
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          # Use different secrets based on environment
          SERVER_HOST: ${{ github.ref == 'refs/heads/main' && secrets.PROD_SERVER_HOST || secrets.STAGING_SERVER_HOST }}
          SERVER_USER: ${{ github.ref == 'refs/heads/main' && secrets.PROD_SERVER_USER || secrets.STAGING_SERVER_USER }}
          SERVER_PASS: ${{ github.ref == 'refs/heads/main' && secrets.PROD_SERVER_PASS || secrets.STAGING_SERVER_PASS }}
          DEPLOY_PATH: ${{ github.ref == 'refs/heads/main' && secrets.PROD_DEPLOY_PATH || secrets.STAGING_DEPLOY_PATH }}
          BRANCH_NAME: ${{ github.ref == 'refs/heads/main' && 'main' || 'staging' }}
        run: |
          export SSHPASS=$SERVER_PASS
          sshpass -e ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "cd $DEPLOY_PATH && \
          git checkout $BRANCH_NAME && \
          git pull origin $BRANCH_NAME && \
          composer install --no-interaction --prefer-dist --optimize-autoloader && \
          php artisan optimize:clear && \
          php artisan config:clear && \
          php artisan cache:clear && \
          php artisan migrate --force"
